<a href="https://colab.research.google.com/github/anjha1/Programming-Languages/blob/main/python/Basic%20Of%20Python/6_Numpy_Basics(a_n_jha).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Array Dimensions

1D Array

2D Array

3D Array

In [1]:
import numpy as np     # importing numpy library

In [2]:
A = np.array(5)        # Scalar Array
A

array(5)

In [3]:
np.ndim(A)               # Dimension method

0

In [4]:
One = np.array([1, 2, 3, 4, 5])
Two = np.array([[1, 2, 3], [4, 5, 6]])
Three = np.array([[[1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9], [10, 11, 12]]])

In [5]:
Three

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
Three.shape
np.ndim(Three)

3

In [7]:
np.ndim(One)
np.ndim(Two)
np.ndim(Three)

3

# List vs Numpy Array

In [8]:
list1 = [1,4.0,'apple']                     # List - Different Datatypes
arr = np.array([1, 2, 3, 4, 5])             # Array - Similar Datatypes

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
arr = np.array([1, 2, 3.9, 'apple'])        # Type Conversion

In [11]:
arr

array(['1', '2', '3.9', 'apple'], dtype='<U32')

In [12]:
arr = np.array([1, 2, 3, 4, 5])             # Allows Mathematical Operations

# arr/5
list1/5

TypeError: unsupported operand type(s) for /: 'list' and 'int'

# More Advantages of Numpy Array over list

*   Array consumes less memory
*   Array are faster than lists



# Reshaping arrays

Reshaping means changing the shape of an array.

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])   # 1D Array

# 1D to 2D Array
newarr = arr.reshape(3, 4)


In [14]:
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
# 1D to 3D Array

newarr = arr.reshape(2, 3, 2)    # x,y,z: x = matrix, y = rows, z = cols


In [16]:
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [17]:
# print(newarr)

# Array Indexing

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

In [18]:
arr = np.array([1, 2, 3, 4])              # Accessing 1D Array

print(arr[3])

4


In [19]:
print(arr[0] + arr[1])                 # Addition of 2 elements

3


In [20]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])  # Accessing 2D Array
arr.shape

# print(arr[0, 3])                          # 1st row 4th element
# print(arr[1, 1])                          # 2nd row 5th element
print(arr[1,3])

9


In [21]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])   # Accessing 3D Array

arr3.shape
# print(arr3)
# print(arr3[0, 0, 2])               # 1st matrix, 1st row, 3rd column
# print(arr3[1, 1, 1])               # 1st matrix, 2nd row, 1st column
print(arr3[0,1,0])

4


In [23]:
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
